### ISSUE TITLE
panic serving @: MarshalJSON shouldn't be used, use CodecEncodeSelf instead

### ISSUE THREAD

**Issue by aanm** [weaveworks/scope#1546]
I'm trying to create a plugin. The plugin is supposed to return a `report` in a json format. However that fails since I get a panic.
```go
func weaveScopeReport(w http.ResponseWriter, r *http.Request) {
	report, err := getSuperScopeReport()
	if err != nil {
               log.Error(err)
               return
	}
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(report); err != nil {
               log.Error(err)
               return
       }
}
```

How can I send an answer with the report?

**Comment by tomwilkie** [comment]
Hi André; just to be clear, the problem is in your plugin crashing and not
scope?

You need to use github.com/ugorji/go/codec to marshall reports; are example
can be seen here:

https://github.com/weaveworks/scope/blob/master/probe/appclient/report_publisher.go#L25

Let me know how you get on; help@weave.works is probably a better forum for
this discussion

Thanks

Tom

**Comment by aanm** [comment]
@tomwilkie Thanks for the reply. I changed my code to `codec.NewEncoder(w, &codec.MsgpackHandle{}).Encode(report)` and the panic stopped, however, in `weavescope/api/report` I see this:

```json
"Plugins": [
{
"id": "my-plugin",
"interfaces": null,
"label": "my-plugin",
"status": "error: decoding error: only encoded map or array can be decoded into a struct"
}
],
```

Which is odd since the weave report is initialized as such:
```
func init() {
	weaveRep = report.MakeReport()
	ps := xfer.PluginSpec{
		ID:          "my-plugin",
		Label:       "my-plugin",
		Description: "my-description",
		Interfaces:  []string{"reporter"},
		APIVersion:  "1",
	}
	weaveRep.Plugins.Add(ps)
}
```

**Comment by tomwilkie** [comment]
The plugins are expected to return json, not msgpack, so you'll need to do something like `codec.NewEncoder(gzwriter, &codec.JsonHandle{}).Encode(r)`.

**Comment by aanm** [comment]
@tomwilkie That gets me back to square one.

`MarshalJSON shouldn't be used, use CodecEncodeSelf instead`

**Comment by tomwilkie** [comment]
Hmm, weird; reports should be able to be marshalled to json (we do it here:
https://github.com/weaveworks/scope/blob/master/app/api_report.go#L14 and
here:
https://github.com/weaveworks/scope/blob/master/app/server_helpers.go#L15).
  Could you share the code that causes the panic?

In the mean time, you could update the plugin code (here:
https://github.com/weaveworks/scope/blob/master/probe/plugins/registry.go#L303)
at accept msgpack encoded reports (see here for example of how:
https://github.com/weaveworks/scope/blob/master/app/router.go#L145).  We'd
happily accept such a change as a PR.

**Comment by aanm** [comment]
```go
package main

import (
	"flag"
	"fmt"
	"github.com/ugorji/go/codec"
	"github.com/weaveworks/scope/common/xfer"
	"github.com/weaveworks/scope/report"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
)

var weaveRep report.Report

func init() {
	weaveRep = report.MakeReport()
	ps := xfer.PluginSpec{
		ID:          "my-plugin",
		Label:       "my-plugin",
		Description: "My-description",
		Interfaces:  []string{"reporter"},
		APIVersion:  "1",
	}
	weaveRep.Plugins.Add(ps)
}

func main() {
	hostname, _ := os.Hostname()
	var (
		addr   = flag.String("addr", "/var/run/scope/plugins/my-plugin.sock", "unix socket to listen for connections on")
		hostID = flag.String("hostname", hostname, "hostname of the host running this plugin")
	)
	flag.Parse()

	log.Printf("Starting on %s...\n", *hostID)

	os.Remove(*addr)
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	go func() {
		<-interrupt
		os.Remove(*addr)
		os.Exit(0)
	}()

	listener, err := net.Listen("unix", *addr)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		listener.Close()
		os.Remove(*addr)
	}()

	log.Printf("Listening on: unix://%s", *addr)

	http.HandleFunc("/report", Report)
	if err := http.Serve(listener, nil); err != nil {
		log.Printf("error: %v", err)
	}
}

func Report(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	if err := codec.NewEncoder(w, &codec.JsonHandle{}).Encode(weaveRep); err != nil {
		fmt.Println("error", err)
		return
	}
}
```

**Comment by tomwilkie** [comment]
Hi André

I've run you're code and I couldn't reproduce the panic.  Are you using the
latest code from weaveworks/scope?

One bug I did notice was the line weaveRep.Plugins.Add(ps) should really be
 weaveRep.Plugins = weaveRep.Plugins.Add(ps) as the Plugins datatype is
immutable, and returns a new instance on Add.  Once I fixed this the probe
correctly connected to the plugin.

HTH

Tom

**Comment by aanm** [comment]
@tomwilkie Thanks for trying out. The `weaveRep.Plugins = weaveRep.Plugins.Add(ps)` didn't solve it for me.

Here's what I got:

```bash
$ sudo -E go run main.go -addr /var/run/my-plugin.sock
2016/05/29 07:41:34 Starting on node1...
2016/05/29 07:41:34 Listening on: unix:///var/run/my-plugin.sock
error MarshalJSON shouldn't be used, use CodecEncodeSelf instead
error MarshalJSON shouldn't be used, use CodecEncodeSelf instead
```

```bash
$ docker run --net host -ti -v /var/run/my-plugin.sock:/var/run/scope/plugins/my-plguin.sock weaveworks/scope:0.15.0
<probe> INFO: 2016/05/29 14:41:36.557237 probe starting, version 0.15.0, ID 5833980ed5a2ebcc
<probe> INFO: 2016/05/29 14:41:36.557302 command line: [scope-probe --mode probe]
<probe> INFO: 2016/05/29 14:41:36.557311 publishing to: localhost:4040
<app> INFO: 2016/05/29 14:41:36.558095 app starting, version 0.15.0, ID 219d47c0d847d7db
<app> INFO: 2016/05/29 14:41:36.558163 command line: [scope-app --mode app]
<app> INFO: 2016/05/29 14:41:36.586220 listening on :4040
<probe> ERRO: 2016/05/29 14:41:36.588328 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:36.590559 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:36.590667 conntrack error: exit status 1
<probe> ERRO: 2016/05/29 14:41:36.590515 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Can't open handler
<probe> ERRO: 2016/05/29 14:41:36.590798 conntrack stderr:read |0: bad file descriptor
<probe> INFO: 2016/05/29 14:41:36.595582 plugins: added plugin /var/run/scope/plugins/my-plguin.sock
<probe> ERRO: 2016/05/29 14:41:36.598950 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:36.601122 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:36.601129 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Can't open handler
<probe> ERRO: 2016/05/29 14:41:36.601261 conntrack error: exit status 1
<probe> INFO: 2016/05/29 14:41:36.612844 Control connection to 127.0.0.1:4040 starting
<app> ERRO: 2016/05/29 14:41:36.667054 Error updating weaveDNS, backing off 20s: exit status 1
<probe> ERRO: 2016/05/29 14:41:36.695730 'weave ps' cmd failed: exit status 1
<probe> ERRO: 2016/05/29 14:41:36.696144 Error collecting weave info, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> ERRO: 2016/05/29 14:41:37.597258 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:37.599658 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Can't open handler
<probe> ERRO: 2016/05/29 14:41:37.599699 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:37.599786 conntrack error: exit status 1
<probe> ERRO: 2016/05/29 14:41:37.601478 plugins: /var/run/scope/plugins/my-plguin.sock: /report error: decoding error: EOF
<probe> ERRO: 2016/05/29 14:41:37.604696 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:37.606393 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:37.606452 conntrack error: exit status 1
<probe> ERRO: 2016/05/29 14:41:37.606370 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Can't open handler
<probe> ERRO: 2016/05/29 14:41:37.606501 conntrack stderr:read |0: bad file descriptor
<probe> ERRO: 2016/05/29 14:41:38.606268 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:38.613685 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:38.613741 conntrack error: exit status 1
<probe> ERRO: 2016/05/29 14:41:38.615256 conntrack existingConnections exit error: exit status 1
<probe> ERRO: 2016/05/29 14:41:38.615298 conntrack stderr:read |0: bad file descriptor
<probe> ERRO: 2016/05/29 14:41:38.620160 plugins: /var/run/scope/plugins/my-plguin.sock: /report error: decoding error: EOF
<probe> ERRO: 2016/05/29 14:41:38.621270 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Can't open handler
<probe> ERRO: 2016/05/29 14:41:38.621361 conntrack error: EOF
<probe> ERRO: 2016/05/29 14:41:38.621396 conntrack error: exit status 1
^C/sbin/runsvdir exited with error: signal: interrupt
INFO: 2016/05/29 14:41:38.959380 === received SIGINT/SIGTERM ===
*** exiting
<app> INFO: 2016/05/29 14:41:38.959457 app exiting
```

**Comment by aanm** [comment]
This works with "github.com/ugorji/go/codec" weavescope vendor libs.
Thanks @tomwilkie
