### ISSUE TITLE
Pipe should allow me to type all characters

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#748]
On UK keyboards I have to use `Right-Alt + 3` to type `#`. These don't seem to be sent.

It also seems that `Ctrl + {arrow}` keys are ignored.

Found in #650

**Comment by paulbellamy** [comment]
Still fails handling most UTF-8 characters (e.g. ì, ÷, §, etc...)

**Comment by tomwilkie** [comment]
ctrl-a (go to beginning of line) was also failing for me, although that
might have been fixed.

**Comment by foot** [comment]
Yep!

Working:
- <kbd>ctrl-a</kbd> / <kbd>ctrl-e</kbd>
- <kbd>alt-3</kbd> -> `#` w/ a UK kb layout
- <kbd>alt-b</kbd> / <kbd>alt-f</kbd> (emacs/readline alias for <kbd>ctrl-leftarrow</kbd> / <kbd>ctrl-rightarrow</kbd>)

Sort of working:
- <kbd>ctrl-n</kbd> / <kbd>ctrl-p</kbd> (need to do them twice?!)

Not working:
- <kbd>ctrl-leftarrow</kbd> / <kbd>ctrl-rightarrow</kbd>
- `cat`ing a file w/ unicode in it
- typing in some unicode

**Comment by foot** [comment]
We're getting latin-1 encoded stuff coming down the line?! (So says wireshark). I can hack around this in JS but it would be nice to get good old utf8!

Do you guys have encoding options when attaching/execing? I'm not sure which part of the system is doing the encoding.

**Comment by foot** [comment]
Okay I got a bit confused there, we just weren't decoding it properly in the JS.

Happy days!

**Comment by paulbellamy** [comment]
Unicode seems fixed, but re-opening as <kbd>ctrl-arrow</kbd> keys still don't work.

**Comment by foot** [comment]
I can get them going by faking a <kbd>alt-f</kbd><kbd>alt-b</kbd>, but term.js seems to do something funny w/ 5C/5D. I wonder if that will causes any issues w/ any apps. Might do. Will do a little more poking.

**Comment by foot** [comment]
@paulbellamy does <kbd>ctrl-arrow</kbd> work when you do a 

`docker exec -ti alpine2 /bin/sh`
?

It doesn't work for me under osx, but ppl say osx is not good at <kbd>ctrl-arrow</kbd>.

**Comment by paulbellamy** [comment]
I was using `docker exec -ti alpine2 /bin/sh`, then running:
```sh
apk update --add zsh && zsh
$ a very long line
```
then using <kbd>ctrl-arrow</kbd> to navigate left-right, as I know how that acts in zsh (I'm less familiar with sh/bash).

It could very well be an osx issue.

**Comment by foot** [comment]
@paulbellamy found a good little test, can you try this:

```
$ docker exec -ti myalpine /bin/sh
/ # zsh
fa07efbe3b94# cat > /dev/null
```
and then type:
<kbd>left-arrow</kbd>
<kbd>right-arrow</kbd>
<kbd>ctrl-left-arrow</kbd>
<kbd>ctrl-right-arrow</kbd>

I see:
`^[[C^[[D^[OC^[OD`

What do you see?

**Comment by paulbellamy** [comment]
```
$ docker run --rm -ti --name alpine alpine /bin/sh
/ # apk add --update zsh
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/3) Installing ncurses-terminfo-base (5.9-r3)
(2/3) Installing ncurses-widec-libs (5.9-r3)
(3/3) Installing zsh (5.0.7-r0)
Executing zsh-5.0.7-r0.post-install
Executing busybox-1.23.2-r0.trigger
OK: 14 MiB in 18 packages
/ # zsh
c4937b04363f# cat >/dev/null
^[[D^[[C^[[1;5D^[[1;5C
```

When doing an exec into the container from scope, I see:

```
/ # zsh                                                                                                              
c4937b04363f# cat >/dev/null                                                                                         
^[[D^[[C^[[5D^[[5C
```

**Comment by foot** [comment]
**Alpine**

sh: (aka Busybox sh aka ash): 

Can't figure out how to list bindings, but seems to understand at least: `[1;5C` and `\ef`.

Bash:
```
bash-4.3# bind -P|grep "^forward-word"                                                                               
forward-word can be found on "\ef".
```
zsh:
```
fa07efbe3b94# bindkey|grep "forward-word"                                                                            
"^[F" forward-word                                                                                                   
"^[f" forward-word
```

**Ubuntu**

sh:

Can't figure out how to list bindings, but doesn't seem to understand anything.

Ubuntu bash:
```
root@8e0bcc4e49be:/# bind -P|grep "^forward-word"                                                                    
forward-word can be found on "\M-\M-[C", "\M-[1;5C", "\M-[5C", "\M-f".                                               
```

Ubuntu zsh:

Can't get `apt-get install` going in a container yet. *sigh*.

**Conclusion**

`m-f` seems to be the safest bet and I can't really think of a case where it would be bad to fake it, but there might be one, second safest/most legit bet is seems to be 1;5C. Lets do that!

**Comment by foot** [comment]
Seems like alpine might add more keybinding support soon https://bugs.alpinelinux.org/issues/4904 https://bugs.alpinelinux.org/issues/4904
